// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyVideoGames.DataContext;

#nullable disable

namespace MyVideoGames.DataContext.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20231214081332_GameWithPlatform")]
    partial class GameWithPlatform
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyVideoGames.Model.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "description_raw");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "platformid");

                    b.Property<int>("PlayTime")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "playtime");

                    b.Property<float>("Rating")
                        .HasColumnType("real")
                        .HasAnnotation("Relational:JsonPropertyName", "rating");

                    b.Property<int>("RatingTop")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "rating_top");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "released");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "slug");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "GTA V",
                            PlatformId = 1,
                            PlayTime = 105,
                            Rating = 5f,
                            RatingTop = 5,
                            ReleaseDate = new DateTime(2023, 12, 14, 9, 13, 31, 738, DateTimeKind.Local).AddTicks(3480),
                            Slug = ""
                        });
                });

            modelBuilder.Entity("MyVideoGames.Model.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.ToTable("Platforms");

                    b.HasAnnotation("Relational:JsonPropertyName", "platform");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Xbox One"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Playstation 5"
                        },
                        new
                        {
                            Id = 3,
                            Name = "PC"
                        });
                });

            modelBuilder.Entity("MyVideoGames.Model.Game", b =>
                {
                    b.HasOne("MyVideoGames.Model.Platform", "Platform")
                        .WithMany("RelatedGames")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("MyVideoGames.Model.Platform", b =>
                {
                    b.Navigation("RelatedGames");
                });
#pragma warning restore 612, 618
        }
    }
}
