// <auto-generated />
using System;
using AirFrance.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirFrance.DataContext.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AirFrance.Model.Passager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCheckedId")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TicketPrice")
                        .HasColumnType("real");

                    b.Property<int>("VolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VolId");

                    b.ToTable("Passagers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = new DateTime(2002, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jules",
                            IsCheckedId = true,
                            LastName = "ROTILIO",
                            TicketPrice = 50f,
                            VolId = 1
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateTime(1999, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Enzo",
                            IsCheckedId = true,
                            LastName = "ROTILIO",
                            TicketPrice = 50f,
                            VolId = 1
                        });
                });

            modelBuilder.Entity("AirFrance.Model.Vol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelayed")
                        .HasColumnType("bit");

                    b.Property<float>("NetSales")
                        .HasColumnType("real");

                    b.Property<string>("OnBoardingMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("TakeOffDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Vols");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Destination = "USA",
                            IsDelayed = true,
                            NetSales = 50000f,
                            OnBoardingMessage = "welcome to the flight to the USA",
                            SeatCount = 80,
                            TakeOffDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AirFrance.Model.Passager", b =>
                {
                    b.HasOne("AirFrance.Model.Vol", "Vol")
                        .WithMany("Passagers")
                        .HasForeignKey("VolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vol");
                });

            modelBuilder.Entity("AirFrance.Model.Vol", b =>
                {
                    b.Navigation("Passagers");
                });
#pragma warning restore 612, 618
        }
    }
}
